name: Minify JavaScript

on: [push]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Minify JavaScript
        run: |
          npm install --global terser
          terser src/file_name.js --output src/file_name.min.js
